sudo: false

cache:
  directories:
  - $HOME/.stack/
  - bower_components
  - output

language: csharp

mono:
  - latest

script:
  - ./build.sh test
  - pulp test
  - travis_wait stack --no-terminal test

install:
  - nvm install $NODE_VERSION
  - npm install -g bower purescript pulp
  - bower install
  - travis_wait stack --no-terminal --install-ghc test --only-dependencies

addons:
  apt:
    packages:
      - libgmp-dev

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
